---
- hosts: localhost
  vars:
    my_home: "{{ lookup('env', 'HOME') }}"
  become: yes
  tasks:
    - name: install yum packages
      when: ansible_distribution == "CentOS" or ansible_distribution == "Red Hat Enterprise Linux"
      yum: name="{{ item }}" state=latest
      with_items:
        - epel-release
        - zsh
        - cmake
        - git
        - tig
        - ctags-etags
        - libevent
        - gcc
        - gcc-c++
        - python-pygments
        - ncurses-devel
        - ncurses
        - wget
        - automake
        - libevent-devel

    - name: install apt packages
      when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"
      apt: name="{{ item }}" state=latest
      with_items:
        - zsh
        - libevent-dev

    - name: clone tmux from GitHub
      git: repo=https://github.com/tmux/tmux dest="{{ my_home }}/dotfiles/tmux"

    - name: configure tmux
      command: "{{ item }}"
      args:
        chdir: "{{ my_home }}/dotfiles/tmux"
      with_items:
        - "sh ./autogen.sh"
        - "./configure"
        - "make"

    - name: copy dots
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items:
        - {src: "{{ my_home }}/dotfiles/.tmux.conf", dest: "{{ my_home }}/.tmux.conf"}
        - {src: "{{ my_home }}/dotfiles/.emacs", dest: "{{ my_home }}/.emacs"}
        - {src: "{{ my_home }}/dotfiles/.emacs.d", dest: "{{ my_home }}/.emacs.d directory_mode=yes"}
        - {src: "{{ my_home }}/dotfiles/.zshrc", dest: "{{ my_home }}/.zshrc"}

    - name: get files
      get_url:
        url: "{{ item.url }}"
        dest: "{{ item.dest }}"
      with_items:
        - {url: "http://tamacom.com/global/global-6.5.6.tar.gz", dest: "{{ my_home }}/dotfiles/"}
        - {url: "https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh",  dest: "{{ my_home }}/dotfiles/"}
      
     
        
        
      
